# Generated by Django 4.2.3 on 2023-08-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=400)),
                ('carga_horaria', models.IntegerField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minieventos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.minievento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=150)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.programacao')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minievento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.minievento')),
            ],
        ),
    ]
